name: 'Update status'
description: 'Update status'
inputs:
  sha:
    description: 'SHA to update'
    required: true
  state:
    description: 'state to update'
    required: true

runs:
  using: "composite"
  steps:
    # It's difficult to get the URL of the current job.
    # The /jobs API and/or the `github` context are misaligned.
    # The duckdbneo repository contains several failed attempts.
    - run: |
        set -x
        if [ -n '${{ inputs.sha }}' ]; then
          export GH_TOKEN=${{ github.token }}

          html_url=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .html_url)

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
            -f "state=${{ job.status }}" -f "target_url=$html_url" -f "description=${{ github.workflow }} / ${{ github.job }}" -f "context=actions-sync"
        fi
      shell: bash
