on:
  push:
    branches:
    - master
    - main
    - "docs*"
    - "cran-*"
    - "r-*"
    tags:
    - "v*"
  pull_request:
    branches:
      - main
      - master
      - "r-*"
  schedule:
    - cron:  '20 0 * * *'

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04

    # Begin custom: services
    # End custom: services
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Check rate limits
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash

      - uses: actions/checkout@v2

      - name: Install pkgdown sysdeps
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          # Needed because of install-r: false
          sudo apt-get update
          # For some reason harfbuzz and gert are installed from source and needs this
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev libgit2-dev

      - name: Configure Git identity
        if: github.event_name == 'push'
        run: |
          env | sort
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        shell: bash

      # Begin custom: before install
      # End custom: before install

      - uses: r-lib/actions/setup-r@v1
        with:
          install-r: false

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install remotes
        run: |
          if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl")
          if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
        shell: Rscript {0}

      - name: Query dependencies
        if: runner.os != 'Windows'
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, type = .Platform$pkgType), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'req <- remotes::system_requirements("ubuntu", "18.04"); if (length(req) > 0) cat(req, sep = "\n")')

      - name: Add fake qpdf and checkbashisms
        if: runner.os == 'Linux'
        run: |
          sudo ln -s $(which true) /usr/local/bin/qpdf
          sudo ln -s $(which true) /usr/local/bin/checkbashisms

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE, type = .Platform$pkgType)
          remotes::install_github("r-lib/pkgdown")
          # Begin custom: dep install
          # End custom: dep install
        shell: Rscript {0}

      # Begin custom: install
      # End custom: install

      - name: Session info
        run: |
          options(width = 100)
          if (!requireNamespace("sessioninfo", quietly = TRUE)) install.packages("sessioninfo")
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # Begin custom: after install
      # End custom: after install

      - name: Install package
        run: R CMD INSTALL . --with-keep.source --with-keep.parse.data

      - name: Deploy package
        if: github.event_name == 'push'
        run: |
          pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}

      - name: Build site
        if: github.event_name != 'push'
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Check rate limits
        if: always()
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash
